# Generated by Django 2.0.7 on 2021-03-24 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('character', models.CharField(max_length=50, null=True)),
                ('job', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LocationContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('moviedb_id', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('tagline', models.CharField(max_length=50)),
                ('rating', models.PositiveIntegerField(null=True)),
                ('votes', models.PositiveIntegerField(null=True)),
                ('popularity', models.FloatField(null=True)),
                ('release_date', models.DateField(null=True)),
                ('budget', models.PositiveIntegerField(null=True)),
                ('profit', models.PositiveIntegerField(null=True)),
                ('duration', models.PositiveIntegerField(null=True)),
                ('is_series', models.NullBooleanField()),
                ('poster_path', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('popularity', models.FloatField()),
                ('imdb_id', models.CharField(max_length=50, null=True)),
                ('gender', models.IntegerField()),
                ('bio', models.CharField(max_length=100)),
                ('birth_place', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50, null=True)),
                ('region', models.CharField(max_length=5, null=True)),
                ('is_original', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='locationcontract',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.Movie'),
        ),
        migrations.AddField(
            model_name='contract',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.Movie'),
        ),
        migrations.AddField(
            model_name='contract',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.Person'),
        ),
        migrations.AddField(
            model_name='category',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.Genre'),
        ),
        migrations.AddField(
            model_name='category',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.Movie'),
        ),
    ]
