# Generated by Django 2.0.7 on 2021-03-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_auto_20210324_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='votes',
            field=models.FloatField(null=True),
        ),
    ]
