# Generated by Django 2.0.7 on 2021-03-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0005_movie_background_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_path',
            field=models.CharField(default=None, max_length=50,null=True),
            preserve_default=False,
        ),
    ]
