# Generated by Django 2.0.7 on 2021-03-28 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0007_auto_20210328_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='profile_path',
            new_name='image_path',
        ),
    ]
