# Generated by Django 2.0.7 on 2021-03-20 15:25

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_type', models.CharField(choices=[('DIRECTOR', ('DIRECTOR',)), ('ACTOR', ('ACTOR',)), ('WRITER', ('WRITER',))], max_length=250)),
                ('star', models.NullBooleanField(default=False)),
                ('role', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilmingLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LocationContract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filming_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.FilmingLocation')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=None, null=True)),
                ('rating', models.FloatField(default=0, null=True)),
                ('votes', models.IntegerField(default=True, null=True)),
                ('reviews', models.IntegerField(default=None, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('release_day', models.DateField(default=None, null=True)),
                ('country', models.CharField(default=None, max_length=50, null=True)),
                ('language', models.CharField(default=None, max_length=50, null=True)),
                ('budget', models.PositiveIntegerField(default=None, null=True)),
                ('total_gross', models.PositiveIntegerField(default=None, null=True)),
                ('duration', models.IntegerField(default=0, null=True)),
                ('is_series', models.NullBooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imdb_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=4)),
                ('original', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='locationcontract',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.Movie'),
        ),
        migrations.AddField(
            model_name='contract',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.Movie'),
        ),
        migrations.AddField(
            model_name='contract',
            name='personality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.Personality'),
        ),
        migrations.AddField(
            model_name='category',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.fields.CharField, to='movieapp.Genre'),
        ),
        migrations.AddField(
            model_name='category',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.Movie'),
        ),
    ]
